baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Luke Hoban'
theme = 'hugo-vitae'

[params]
	# Enable dark mode as default
	#darkmode = true

	# Use homepage.md instead of a list of posts
	homepage = false

	# Add meta keywords in head part (Site Keywords or Tags of Page)
	#keywords = ["hugo","vitae","theme","static"]

	# Add meta description in head part
	#description = "Vitae is a blog theme for Hugo that focuses on your content."

	# Add pagetitle to homepage <title> tag
	#pagetitle = "All about static site generation"

	# Add a subtitle to your website
	#subtitle = "[Vitae](https://github.com/dataCobra/hugo-vitae) is a blog theme for Hugo that focuses on your content."

	# Add math typesetting with KaTeX (Global with this Param)
	math = true